# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main  # or 'master', or any branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (example)
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Configure Datadog Test Optimization
      uses: datadog/test-visibility-github-action@v2
      with:
        languages: js
        api_key: ${{secrets.DD_API_KEY}}
        site: us5.datadoghq.com
    - name: Run tests
      shell: bash
      run: npm test
    env:
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      DD_SITE: us5.datadoghq.com
      NODE_OPTIONS: --require dd-trace/init
